# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  product-catalog-crawler:
    image: product-catalog-crawler:latest
    ports:
      - "8081:8080"
